services:
  - type: web
    name: northcross-api
    env: python
    plan: free
    rootDir: api          # ðŸ‘ˆ le dice a Render que el cÃ³digo estÃ¡ dentro de /api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn northcross_api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000

